config_version: 1.0
training:
  trainer: mmf # lightning_gaif
  seed: 1
  experiment_name: run
  max_updates: null
  max_epochs: 80
  log_interval: 100
  logger_level: error
  log_format: json
  log_detailed_config: true
  should_not_log: false
  colored_logs: true
  tensorboard: true
  batch_size: 32
  batch_size_per_device: null
  update_frequency: 1
  num_workers: 4
  fast_read: true
  dataset_size_proportional_sampling: true
  pin_memory: true
  checkpoint_interval: 1500
  evaluation_interval: 1500
  clip_gradients: false
  clip_norm_mode: all
  early_stop:
    enabled: false
    patience: 4000
    criteria: total_loss
    minimize: true
  lr_scheduler: false # true this later
  lr_steps: []
  lr_ratio: 0.1
  use_warmup: false
  warmup_factor: 0.2
  warmup_iterations: 1000
  device: cuda
  local_rank: null
  verbose_dump: false
  find_unused_parameters: false
  evaluate_metrics: false
  detect_anomaly: false
  fp16: false
  callbacks: []
  exit_on_nan_losses: true
trainer:
  type: lightning_gaif
  params:
    gpus: 1
    num_nodes: 1
    precision: 32
    deterministic: false
    benchmark: false
    max_steps: null
    max_epochs: 80
    gradient_clip_val: 0.0
    num_sanity_val_steps: 0
    checkpoint_callback: true
    accumulate_grad_batches: 1
    val_check_interval: 300
    log_every_n_steps: 100
    logger: true
    limit_val_batches: 1.0
    progress_bar_refresh_rate: 1
    fast_dev_run: false
    resume_from_checkpoint: null
evaluation:
  metrics:
  - accuracy
  use_cpu: false
  predict: false
  predict_file_format: json
  reporter:
    type: file
    params: {}
model_config:
  model_timm:
    model: model_timm
    model_library: null
    pretrained: false
    losses:
    - type: cross_entropy
    params:
      model_name: resnet50
      checkpoint_path: null
      pretrained: true
  model_torchvision:
    model: model_torchvision
    model_library: resnet50
    pretrained: false
    losses:
    - type: cross_entropy
  vgg16:
    model: vgg16
    losses:
    - type: cross_entropy
  efficientnet:
    model: efficientnet
    pretrained: true
    pretrained_weights_version: efficientnet-b0
    losses:
    - type: cross_entropy
  simclr:
    model: simclr
    num_ftrs: 512
    losses:
    - type: NTXentLoss
      params:
        temperature: 0.5
    image_encoder:
      type: timm_encoder
      params:
        model_library: mixer_s16_224
        pretrained: false
        fpn: false
        forward_features: true
        pool: false
        pool_type: null
        freeze:
          use_freeze: false
          layers_to_freeze: null
  resnet152_timm:
    model: resnet152_timm
    image_encoder:
      type: timm_encoder
      params:
        model_library: resnet152
        pretrained: false
        fpn: false
        forward_features: true
        pool: true
        pool_type: false
        num_output_features: 1
        pretrained_model: weights/resnet152_sup_torchvision.pth
        freeze:
          use_freeze: false
          layers_to_freeze: null
    classifier:
      type: mlp
      params:
        in_dim: 2048
        out_dim: 10
        hidden_dim: 1000
        num_layers: 1
    losses:
    - type: cross_entropy
  mlp_mixer:
    model: mlp_mixer
    image_encoder:
      type: timm_encoder
      params:
        model_library: mixer_s16_224
        pretrained: false
        fpn: false
        pool: false
        pool_type: false
        num_output_features: 1
        pretrained_model: ./save_ssl_9_august/best.ckpt
        freeze:
          use_freeze: false
          layers_to_freeze: -1
    classifier:
      type: mlp
      params:
        in_dim: 512
        out_dim: 10
        hidden_dim: 300
        num_layers: 1
    losses:
    - type: cross_entropy
dataset_config:
  classification_cifar10:
#    data_dir: /home/imagedpt/.cache/torch/mmf/data
    method: sup
    processors:
      augly_image_transforms:
        type: augly_image_transforms
        params:
          transforms:
          - type: RandomCrop
            params:
              size:
              - 32
              - 32
              padding: 4
          - type: Resize
            params:
              size:
              - 224
              - 224
          - ToTensor
          - RandomHorizontalFlip
          - type: Normalize
            params:
              mean:
              - 0.4914
              - 0.4822
              - 0.4465
              std:
              - 0.2023
              - 0.1994
              - 0.201
      image_transforms:
        type: torchvision_transforms
        params:
          transforms:
          - type: RandomCrop
            params:
              size:
              - 32
              - 32
              padding: 4
          - ToTensor
          - RandomHorizontalFlip
          - type: Normalize
            params:
              mean:
              - 0.4914
              - 0.4822
              - 0.4465
              std:
              - 0.2023
              - 0.1994
              - 0.201
datasets: classification_raf_basic
model: model_timm
config: config_run_example.yaml
run_type: train_inference
optimizer:
  allow_unused_parameters: false
  enable_state_sharding: false
  type: Adam
  params:
    lr: 0.001
    weight_decay: 1.0e-05
scheduler:
  type: one_cycle_lr
  params:
    max_lr: 0.01
    steps_per_epoch: 1876
    epochs: 80
    anneal_strategy: cos
env:
  cache_dir: /home/imagedpt/.cache/torch/mmf
  dataset_zoo: configs/zoo/datasets.yaml
  model_zoo: configs/zoo/models.yaml
  data_dir: /home/imagedpt/.cache/torch/mmf/data
  save_dir: ./save
  log_dir: ''
  report_dir: ''
  tensorboard_logdir: ''
  user_dir: ''
distributed:
  init_method: null
  rank: 0
  port: -1
  backend: nccl
  world_size: 1
  no_spawn: false
checkpoint:
  resume: false
  resume_file: null
  resume_best: false
  resume_pretrained: false
  resume_zoo: null
  zoo_config_override: false
  pretrained_state_mapping: {}
  max_to_keep: 10
  save_git_details: true
  reset:
    all: false
    optimizer: false
    counts: false
    fp16_scaler: false
multitasking:
  enabled: true
  type: size_proportional
  params: {}
collator: collate_base
start_rank: 0
device_id: 0
