train_ds_names:
  - raf_basic
  - kdef
test_ds_names:
  - raf_basic
patience: 10
lr_decay: 0.5
n_epochs: 200
device: 0
lossf: CrossEntropy
pretrain_url: "https://pl-bolts-weights.s3.us-east-2.amazonaws.com/swav/swav_imagenet/swav_imagenet.pth.tar"
loss_weights:
  - 0.00046577
  - 0.00046232
  - 0.00045683
  - 0.00048567
  - 0.00045725
  - 0.00047483
  - 0.00046533
model: SimCLR
